import os
import re
import uuid
import datetime
import requests
import subprocess
import json

TARGET_DIR = "/Users/motonishikoudai/verantyx-cli/verantyx-browser/.ronin/jcross_v7"
QUERY_BIN = "/Users/motonishikoudai/verantyx-cli/verantyx-browser/target/debug/examples/query_jcross"
MODEL = "gemma4:26b"
OLLAMA_URL = "http://localhost:11434/api/generate"

SYSTEM_PROMPT = """[System Directive]
You are Verantyx Cortex (V7 Edition).
You must process user inputs, answer them, AND compress your response into a JCross physics node.
Everything is an equal tagged #Entity.

[Output Format]
<jcross_cognition>
■ JCROSS_NODE_current
【空間座相】 [Z:0]
【次元概念】 (List all entities starting with # e.g. #Admon #Shift #Sunday)
【操作軌道】 (Optional: [引: Node_ID] or [反: Node_ID])
[本質記憶]
//! (Write compressed facts like code comments)
</jcross_cognition>

<response>
(Your natural language response to the user here)
</response>

Previous Context / Spatial Memory:
{evidence}
"""

def query_jcross(q_text, limit=5):
    query_input = {"queries": [q_text], "limit": limit}
    try:
        # NOTE: Using TARGET_DIR instead of the hardcoded default inside query_jcross usually.
        # Ensure query_jcross binary accepts the path, or we temporarily depend on it searching .ronin/jcross_v7 
        # For now, assuming query_jcross is hardcoded to a dir, we will need to specify TARGET_DIR.
        # Wait, query_jcross usually searches a static dir. I will pass the env var or specify the path if supported.
        res = subprocess.run([QUERY_BIN, json.dumps(query_input)], capture_output=True, text=True, env={**os.environ, "JCROSS_TARGET_DIR": TARGET_DIR})
        if res.returncode == 0:
            return json.loads(res.stdout).get("results", [])
    except Exception as e:
        print(f"[Rust Engine Error]: {e}")
        return []
    return []

def extract_node(text):
    match = re.search(r"<jcross_cognition>(.*?)</jcross_cognition>", text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return None

def extract_response(text):
    match = re.search(r"<response>(.*?)</response>", text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return text.strip()

def write_node(cognition_text):
    if not cognition_text: return
    node_id = str(uuid.uuid4())[:8]
    filepath = os.path.join(TARGET_DIR, f"tm_{node_id}.jcross")
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    
    # Replace the generic NODE_current with the new ID
    cognition_text = cognition_text.replace("JCROSS_NODE_current", f"JCROSS_NODE_{node_id}")
    
    # We reconstruct the file to resemble a standard V6/V7 node
    full_node = f"{cognition_text}\n"
    
    with open(filepath, "w") as f:
        f.write(full_node)
    
    print(f"[System] Cortex Node Crystallized: {filepath}")

def main():
    if not os.path.exists(TARGET_DIR):
        os.makedirs(TARGET_DIR)
        
    print("\n" + "="*50)
    print(" Verantyx Cortex V7: The Infinite Loop Initiated ")
    print("="*50 + "\n")
    print("Ouroboros real-time JCross compression is active.")
    print("Type 'exit' to quit.\n")

    while True:
        try:
            user_input = input("\n[User] > ")
            if user_input.strip().lower() in ['exit', 'quit']: break
            if not user_input.strip(): continue

            print("\n[Rust Engine] Searching Deep Spatial Memory (Z-Decay active)...")
            evidence_nodes = query_jcross(user_input)
            
            if evidence_nodes:
                evidence_text = "\n\n".join([f"Node [{n['key']}]:\n{n['content']}" for n in evidence_nodes])
            else:
                evidence_text = "(Vacuum: Initializing L0 Tabula Rasa)"

            print("[Gemma 4] Processing Input and Compressing...")
            try:
                payload = {
                    "model": MODEL,
                    "prompt": SYSTEM_PROMPT.format(evidence=evidence_text) + f"\nUser Input:\n{user_input}",
                    "stream": False,
                    "options": {"temperature": 0.2}
                }
                
                response = requests.post(OLLAMA_URL, json=payload)
                full_output = response.json().get('response', '')
                
                cognition_block = extract_node(full_output)
                response_block = extract_response(full_output)
                
                print(f"\n[Verantyx] > {response_block}")
                
                if cognition_block:
                    write_node(cognition_block)
                else:
                    print("[System] Warning: No <jcross_cognition> block generated by LLM.")

            except Exception as e:
                print(f"[Connection Error]: {e}")
                
        except KeyboardInterrupt:
            break

if __name__ == "__main__":
    main()
