"""
Cross Structure Viewer Panel

Real-time viewer for Cross structure generated by Claude Monitor.
"""

import json
from pathlib import Path
from typing import Optional

from textual.app import App, ComposeResult
from textual.containers import Container, Vertical
from textual.widgets import Header, Footer, Static
from textual.binding import Binding
from rich.panel import Panel
from rich.json import JSON
from rich.tree import Tree
from rich.text import Text


class CrossViewerPanel(Static):
    """Panel to display Cross structure in real-time"""

    def __init__(self, cross_file: Path, **kwargs):
        super().__init__(**kwargs)
        self.cross_file = cross_file
        self.last_modified = 0

    def on_mount(self):
        """Start auto-refresh timer"""
        self.set_interval(3.0, self.update_cross)

    def update_cross(self):
        """Update Cross structure display"""
        if not self.cross_file.exists():
            self.update("[dim]Waiting for Cross structure...[/dim]")
            return

        # Check if file was modified
        current_modified = self.cross_file.stat().st_mtime
        if current_modified == self.last_modified:
            return

        self.last_modified = current_modified

        try:
            with open(self.cross_file, 'r') as f:
                cross_data = json.load(f)

            # Build tree view
            tree = self._build_cross_tree(cross_data)
            self.update(tree)

        except Exception as e:
            self.update(f"[red]Error loading Cross structure: {e}[/red]")

    def _build_cross_tree(self, cross_data: dict) -> Tree:
        """Build tree view of Cross structure"""
        tree = Tree("🧠 Cross Memory (Live)")

        # Timestamp
        timestamp = cross_data.get('timestamp', 'Unknown')
        tree.add(f"[cyan]Updated:[/cyan] {timestamp}")

        # Axes
        axes_node = tree.add("[bold]6-Axis Structure[/bold]")

        axes = cross_data.get('axes', {})

        # UP axis
        up_node = axes_node.add("[green]⬆️  UP (Goals)[/green]")
        up_data = axes.get('up', {})
        for key, value in up_data.items():
            up_node.add(f"[dim]{key}:[/dim] {str(value)[:50]}")

        # DOWN axis
        down_node = axes_node.add("[blue]⬇️  DOWN (Foundations)[/blue]")
        down_data = axes.get('down', {})
        for key, value in down_data.items():
            down_node.add(f"[dim]{key}:[/dim] {value}")

        # FRONT axis
        front_node = axes_node.add("[yellow]➡️  FRONT (Current)[/yellow]")
        front_data = axes.get('front', {})
        activity = front_data.get('current_activity', 'Unknown')
        front_node.add(f"[bold]Activity:[/bold] {activity}")
        if 'recent_user_inputs' in front_data:
            inputs = front_data['recent_user_inputs']
            if inputs:
                front_node.add(f"[dim]Last input:[/dim] {inputs[-1][:40]}...")

        # BACK axis
        back_node = axes_node.add("[magenta]⬅️  BACK (History)[/magenta]")
        back_data = axes.get('back', {})
        session_history = back_data.get('session_history', {})
        if session_history:
            duration = session_history.get('duration', 0)
            back_node.add(f"[dim]Session duration:[/dim] {duration:.0f}s")

        # RIGHT axis
        right_node = axes_node.add("[white]⮕  RIGHT (Expansion)[/white]")
        right_data = axes.get('right', {})
        patterns = right_data.get('learned_patterns', [])
        if patterns:
            for pattern in patterns:
                right_node.add(f"[dim]•[/dim] {pattern}")
        else:
            right_node.add("[dim]No patterns yet[/dim]")

        # LEFT axis
        left_node = axes_node.add("[red]⬅  LEFT (Constraints)[/red]")
        left_data = axes.get('left', {})
        constraints = left_data.get('constraints', [])
        for constraint in constraints[:3]:
            left_node.add(f"[dim]•[/dim] {constraint}")

        return tree


class CrossViewerApp(App):
    """Standalone Cross viewer application"""

    CSS = """
    Screen {
        align: center middle;
    }

    #cross_viewer {
        width: 90%;
        height: 90%;
        border: solid $primary;
        padding: 1;
    }
    """

    BINDINGS = [
        Binding("q", "quit", "Quit"),
        Binding("r", "refresh", "Refresh"),
    ]

    def __init__(self, cross_file: Path, **kwargs):
        super().__init__(**kwargs)
        self.cross_file = cross_file

    def compose(self) -> ComposeResult:
        yield Header(show_clock=True)
        yield CrossViewerPanel(self.cross_file, id="cross_viewer")
        yield Footer()

    def on_mount(self):
        self.title = "Verantyx Cross Structure Viewer"

    def action_refresh(self):
        """Force refresh"""
        viewer = self.query_one("#cross_viewer", CrossViewerPanel)
        viewer.last_modified = 0
        viewer.update_cross()


def view_cross_structure(project_path: Path):
    """View Cross structure in real-time"""
    cross_file = project_path / ".verantyx" / "claude_monitor.cross.json"

    if not cross_file.exists():
        print(f"❌ Cross structure file not found: {cross_file}")
        print("   Start Claude monitoring first: verantyx chat --llm claude")
        return

    app = CrossViewerApp(cross_file=cross_file)
    app.run()
