import Foundation

// MARK: - VeraSkillForge
//
// Fully automatic skill generation from Vera's own answer frequency — no
// human review and no `TwinCriticEngine` audit (unlike the LLM-invoked
// `forgeSkill` AgentTool case, which IS audited before `SkillLibrary`
// saves it — see `AgentTool.swift`'s `.forgeSkill` handler). This is a
// deliberate, narrower choice than that: a core Vera has answered
// `forgeThreshold` times becomes a directly-callable skill, automatically.
//
// Why this is a bounded risk despite skipping review: the generated
// skill's payload is always exactly one `[MCP_CALL: vera-memory.ask]` for
// a core Vera ALREADY holds a typed ANSWER verdict for — this can't
// fabricate a new fact or run an arbitrary action, it only wraps a lookup
// Vera would have answered the same way anyway. The risk this skips
// review for is "a skill nobody asked to have created," not "a false
// fact" or "an unreviewed action."
@MainActor
enum VeraSkillForge {

    private static let countsKey = "vera_core_ask_counts_v1"
    private static let forgeThreshold = 3

    private static func loadCounts() -> [String: Int] {
        (UserDefaults.standard.dictionary(forKey: countsKey) as? [String: Int]) ?? [:]
    }

    private static func saveCounts(_ counts: [String: Int]) {
        UserDefaults.standard.set(counts, forKey: countsKey)
    }

    /// Called from `VeraMemoryBridge.askRaw` after every ANSWER verdict.
    /// Increments the core's count; forges a skill exactly once, the turn
    /// the count crosses `forgeThreshold` (not on every subsequent ask).
    static func recordAnswerAndMaybeForge(core: String) async {
        var counts = loadCounts()
        let n = (counts[core] ?? 0) + 1
        counts[core] = n
        saveCounts(counts)

        guard n == forgeThreshold else { return }

        let skillName = "vera_auto_" + sanitize(core)
        if await SkillLibrary.shared.skill(named: skillName) != nil { return }

        var node = SkillNode(
            name: skillName,
            description: "Auto-generated by Vera-α: answers '\(core)' from Vera's "
                + "deterministic store (asked \(n)+ times) without an LLM call.",
            version: 1,
            createdAt: Date(),
            updatedAt: Date(),
            tags: ["vera-auto", "auto-generated"],
            executionType: .macro,
            payload: ["[MCP_CALL: vera-memory.ask]{\"query\": \"\(core)\"}[/MCP_CALL]"]
        )
        node.source = "vera-auto"
        node.forgedBy = "vera-alpha-autoskill"
        _ = await SkillLibrary.shared.save(node)
    }

    private static func sanitize(_ s: String) -> String {
        let mapped = s.lowercased().map { c -> Character in
            (c.isLetter || c.isNumber) ? c : "_"
        }
        return String(String(mapped).prefix(40))
    }
}
