import re
from typing import List, Dict, Any

class JCrossExtractionParser:
    """
    Parses V7.1 JCross Semantic Fragments generated by the Puzzle IR Builder.
    This uses a fault-tolerant Regex system to handle non-strict LLM outputs 
    (from smaller models that might inject markdown bullets or colons).
    """
    
    @staticmethod
    def parse(llm_output: str) -> List[Dict[str, Any]]:
        fragments = []
        
        # 1. Find all fragment blocks by looking for ■ JCROSS_FRAG_{id} globally
        # The block continues until the next ■ JCROSS_FRAG_ or end of string
        block_pattern = re.compile(r"■\s*JCROSS_FRAG_([a-zA-Z0-9_-]+)(.*?)(?=■\s*JCROSS_FRAG_|$)", re.DOTALL)
        
        for block_match in block_pattern.finditer(llm_output):
            frag_id = "JCROSS_FRAG_" + block_match.group(1).strip()
            block_content = block_match.group(2)
            
            # Helper to extract values for tags
            def extract_tag(tag_names: List[str]) -> str:
                """
                Extracts the value following the tag up to the next tag or end of string.
                Strips out common noisy markdown like colons or dashes.
                """
                for tag in tag_names:
                    # Look for the tag, then capture everything until the next 【 or end
                    pattern = rf"【{tag}】[\s:*-]*(.*?)(?=【|$)"
                    match = re.search(pattern, block_content, re.DOTALL)
                    if match:
                        val = match.group(1).strip()
                        # Remove trailing markdown list bullets if they got caught before the next tag
                        val = re.sub(r"[\r\n]+\s*[-*]+\s*$", "", val)
                        # Limit to a reasonable size and remove newlines for pure facts
                        val = " ".join(val.split())
                        if len(val) > 200:
                            val = val[:197] + "..."
                        return val
                return None

            source = extract_tag(["源泉", "Source", "source"])
            subject = extract_tag(["主体", "Subject", "subject"])
            predicate = extract_tag(["関係", "Predicate", "predicate"])
            obj = extract_tag(["客体", "Object", "object"])
            context = extract_tag(["文脈", "Context", "context"])
            state = extract_tag(["状態", "State", "state"])
            
            # Special handling for trace
            trace_raw = extract_tag(["軌道", "Trace", "trace"])
            trace_id = None
            if trace_raw:
                trace_match = re.search(r"\[[遡遡溯Trace]+:\s*(.+?)\]", trace_raw)
                if trace_match:
                    trace_id = trace_match.group(1).strip()
                elif "idx_" in trace_raw:
                    # Fallback if they write 【軌道】 idx_99
                    idx_match = re.search(r"(idx_\d+)", trace_raw)
                    if idx_match:
                        trace_id = idx_match.group(1)

            # Special handling for L2 Lossless Archive
            l2_raw = None
            l2_match = re.search(r"\[L2_Archive\]\s*(.*?)(?=\n\[|\Z)", block_content, re.DOTALL)
            if l2_match:
                l2_raw = l2_match.group(1).strip()

            fragments.append({
                "__id__": frag_id,
                "source": source,
                "subject": subject,
                "predicate": predicate,
                "object": obj,
                "context": context,
                "state": state,
                "trace": trace_id,
                "l2_raw": l2_raw
            })
            
        return fragments
